trials:
  - date: "2020-03-12"
    group: "control"
    rod: "W"
    coupon: "A1"
    joint: "paste"
    comment: ""

  - date: "2021-01-14"
    group: "control"
    rod: "W"
    coupon: "A2"
    joint: "paste"
    comment: ""

  - date: "2021-02-23"
    group: "control"
    rod: "W"
    coupon: "A2"
    joint: "paste"
    comment: ""

  - date: "2021-03-09"
    group: "control"
    rod: "W"
    coupon: "A2"
    joint: "paste"
    comment: ""

  - date: "2021-03-25"
    group: "control"
    rod: "W"
    coupon: "A3"
    joint: "paste"
    comment: ""

  - date: "2021-03-29"
    group: "control"
    rod: "W"
    coupon: "A3"
    joint: "paste"
    comment: ""

  - date: "2021-04-15"
    group: "control"
    rod: "W"
    coupon: "A3"
    joint: "paste"
    comment: ""

  - date: "2021-04-28"
    group: "control"
    rod: "W"
    coupon: "A4"
    joint: "paste"
    comment: A4-1

  - date: "2021-04-29"
    group: "control"
    rod: "W"
    coupon: "A4"
    joint: "paste"
    comment: A4-2

  - date: "2021-04-30"
    group: "control"
    rod: "W"
    coupon: "A4"
    joint: "paste"
    comment: A4-3

  - date: "2021-06-16"
    group: "control"
    rod: "W"
    coupon: "A4"
    joint: "paste"
    comment: A4-4. See "21.09.03 Progress.pptx".

  - date: "2021-06-17"
    group: "control"
    rod: "W"
    coupon: "A4"
    joint: "paste"
    comment: A4-5. See "21.09.03 Progress.pptx".

  - date: "2021-06-21"
    group: "control"
    rod: "W"
    coupon: "A4"
    joint: "paste"
    comment: A4-6

  - date: "2021-06-22"
    group: "control"
    rod: "W"
    coupon: "A4"
    joint: "paste"
    good: false
    comment: Second day water intrusion

  - date: "2021-08-30"
    group: "control"
    rod: "W"
    coupon: "A4"
    joint: "paste"
    good: false
    comment: Poorly-wrapped sample

  - date: "2021-08-31"
    group: "control"
    rod: "W"
    coupon: "A4"
    joint: "paste"
    comment: A4-7

  - date: "2021-09-29"
    group: "control"
    rod: "W"
    coupon: "A4"
    joint: "epoxy"
    comment: Silver epoxy. Separated during this trial.  Need to cure at higher temp. See <https://trello.com/c/mlVNKOQm/28-bond-sample-a4-to-post-0>. A4-12.

  - date: "2021-10-12"
    group: "control"
    rod: "W"
    coupon: "A4"
    joint: "epoxy"
    comment: First run with silver epoxy cured at higher temperature. Vertical anomaly. See "21.10.15 Progress.pptx". See <https://trello.com/c/L6AmQDJR/26-bond-sample-a4-to-warped-post>. A4-13. High T_s_err and non-monotonic.
    good: false

  - date: "2021-10-13"
    group: "control"
    rod: "W"
    coupon: "A4"
    joint: "epoxy"
    comment: Second run with silver epoxy cured at higher temperature. See "21.10.15 Progress.pptx". A4-14. Broke clean off after trial, see <https://trello.com/c/8w9swkNl/19-run-experiment-a4>. High T_s_err and non-monotonic.
    good: false

  - date: "2021-12-09"
    group: "control"
    rod: "Y"
    coupon: "A7"
    joint: "epoxy"
    comment: See "22.01.07 Progress.pptx". Epoxy stays intact?

  - date: "2022-01-06"
    group: "control"
    rod: "Y"
    coupon: "A7"
    joint: "epoxy"
    comment: Duralco 132-1. See "22.01.07 Progress.pptx". Still, there's a minor vertical jump.

  - date: "2022-01-19"
    group: "porous"
    rod: "X"
    coupon: "A6"
    sample: "B3"
    joint: "epoxy"
    comment: Copper X-A6-B3-1. Duralco 132-1. Epoxy failed during this trial?

  - date: "2022-01-20"
    group: "porous"
    rod: "X"
    coupon: "A6"
    sample: "B3"
    joint: "epoxy"
    good: false
    comment: Copper X-A6-B3-2. Duralco 132-1. See "22.01 Report.docx". Epoxy intact based on observation in <https://trello.com/c/qH01qs50/43-run-experiment-x-a6-b3>. Detached B3 after this trial.

  - date: "2022-03-29"
    group: "control"
    rod: "X"
    coupon: "A6"
    joint: "solder"
    comment: Copper X-A6-fail2. fail1 has no data, see "Other". First trial with data since detaching B3 and making X-A6 a solder joint. For some reason, can't get all results from "2022-03-29T14-01-41".

  - date: "2022-04-08"
    group: "control"
    rod: "X"
    coupon: "A9"
    joint: "solder"
    comment: Copper X-A9-newcam

  - date: "2022-08-16"
    group: "control"
    rod: "R"
    coupon: "A0"
    joint: "none"
    comment: "First trial with the jointless rod. There was an issue with T1 and T2 not being installed deeply enough for runs prior to 12-16-38."
    good: false

  - date: "2022-09-08"
    group: "control"
    rod: "R"
    coupon: "A0"
    joint: "none"
    comment: "Second trial with jointless rod. Ended up testing the same point multiple times, trying different things outlined in the Trello note."
    good: false

  - date: "2022-09-14"
    group: "control"
    rod: "R"
    coupon: "A0"
    joint: "none"
    comment: "RTV has been applied on the cylindrical sidewall of the copper post."
    good: false
    new: true
