name: "publish"
on:
  workflow_dispatch: {}
  release:
    types:
      - "published"
      - "released"

jobs:
  publish:
    runs-on: "windows-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.0.9"
        with:
          python-version: "3.10"
      - run: "flit publish"
        env:
          FLIT_USERNAME: "__token__"
          FLIT_PASSWORD: "${{ secrets.PYPI_TOKEN }}"
